#!/usr/bin/env bash
# Simple demo script for a client to exercise You.fyi features
# Usage: BASE_URL=http://localhost:8001 ./client_demo.sh
# If deploying to Render, set BASE_URL to your deployment URL.

set -euo pipefail
BASE_URL=${BASE_URL:-http://localhost:8001}

echo "You.fyi Client Demo"
echo "Base URL: $BASE_URL"

# 1) Create a workspace (use a unique name to avoid UNIQUE constraint from prior runs)
WS_NAME="Client Demo Workspace $(date +%s)"
WS_DESC="Workspace created via client demo"
echo "\n1) Creating workspace: $WS_NAME"
WS_RESPONSE=$(curl -s -X POST "$BASE_URL/workspaces/" \
  -H "Content-Type: application/json" \
  -d "{\"name\":\"$WS_NAME\",\"description\":\"$WS_DESC\"}")
WS_ID=$(echo "$WS_RESPONSE" | python3 -c "import sys, json; obj=json.load(sys.stdin); print(obj.get('id',''))")
if [ -z "$WS_ID" ]; then
  echo "Create workspace response did not include id; showing full response:" >&2
  echo "$WS_RESPONSE" >&2
  echo "Attempting to find workspace by name..."
  # fallback: list workspaces and try to match by name
  WS_ID=$(curl -s "$BASE_URL/workspaces" | python3 - <<'PY'
import sys, json
ws_name = sys.argv[1]
arr = json.load(sys.stdin)
for w in arr:
    if w.get('name') == ws_name:
        print(w.get('id'))
        sys.exit(0)
sys.exit(0)
PY
  "$WS_NAME")
fi
echo "Workspace created: $WS_ID"

# 2) Create a text asset
echo "\n2) Creating a text asset..."
TEXT_RESPONSE=$(curl -s -X POST "$BASE_URL/assets/$WS_ID" \
  -H "Content-Type: application/json" \
  -d '{"name":"Intro Doc","description":"Intro created from demo","content":"This is sample content to demonstrate You.fyi","asset_type":"document"}')
TEXT_ID=$(echo "$TEXT_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('id',''))")
echo "Text asset id: $TEXT_ID"

# 3) Upload a small sample file (if file path passed as first arg), otherwise create a small sample PDF and upload it.
SAMPLE_FILE="${1:-}" 
if [ -z "$SAMPLE_FILE" ]; then
  echo "No file path provided; generating a small PDF at /tmp/youfyi_demo.pdf"
  python3 - <<'PY'
from reportlab.pdfgen import canvas
c = canvas.Canvas('/tmp/youfyi_demo.pdf')
c.drawString(100,750,'You.fyi Demo PDF')
c.drawString(100,730,'Generated by client_demo.sh')
c.save()
print('/tmp/youfyi_demo.pdf')
PY
  SAMPLE_FILE="/tmp/youfyi_demo.pdf"
fi

echo "\n3) Uploading file: $SAMPLE_FILE"
UPLOAD_RESPONSE=$(curl -s -X POST "$BASE_URL/assets/$WS_ID/upload" -F "file=@$SAMPLE_FILE" -F "description=Demo upload from client script")
UPLOAD_ID=$(echo "$UPLOAD_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('id',''))")
echo "Uploaded asset id: $UPLOAD_ID"

# 4) List assets in workspace
echo "\n4) Listing assets in workspace"
curl -s "$BASE_URL/assets/$WS_ID" | python3 -m json.tool

# 5) Create a kit
echo "\n5) Creating kit"
KIT_RESPONSE=$(curl -s -X POST "$BASE_URL/kits/$WS_ID" \
  -H "Content-Type: application/json" \
  -d '{"name":"Demo Kit","description":"Kit created via demo"}')
KIT_ID=$(echo "$KIT_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('id',''))")
echo "Kit created: $KIT_ID"

# 6) Add assets to kit
echo "\n6) Adding assets to kit"
ASSET_IDS_JSON=$(curl -s "$BASE_URL/assets/$WS_ID" | python3 -c "import sys, json; a=json.load(sys.stdin); print(json.dumps({'asset_ids':[x['id'] for x in a]}))")

# Use curl to capture HTTP code and body; handle 204 No Content gracefully
TMP_OUT=$(mktemp)
HTTP_CODE=$(curl -s -w "%{http_code}" -o "$TMP_OUT" -X PUT "$BASE_URL/kits/kit/$KIT_ID" -H "Content-Type: application/json" -d "$ASSET_IDS_JSON")
if [ "$HTTP_CODE" = "204" ]; then
  echo "Assets added to kit (204 No Content)"
  rm -f "$TMP_OUT"
else
  cat "$TMP_OUT" | python3 -m json.tool || cat "$TMP_OUT"
  rm -f "$TMP_OUT"
fi

# 7) Create sharing link
echo "\n7) Creating sharing link (7 days)"
SHARE_RESPONSE=$(curl -s -X POST "$BASE_URL/sharing-links/kit/$KIT_ID" -H "Content-Type: application/json" -d '{"expires_in_days":7}')
SHARE_TOKEN=$(echo "$SHARE_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('token',''))")
echo "Sharing token: $SHARE_TOKEN"

# 8) Run a RAG query (will use server-side OpenAI if configured)
echo "\n8) Running a RAG query against the kit"
RAG_RESPONSE=$(curl -s -X POST "$BASE_URL/rag/query" -H "Content-Type: application/json" -d "{\"query\":\"Give a short summary of the assets\",\"kit_id\":\"$KIT_ID\",\"use_llm\":true}")
echo "$RAG_RESPONSE" | python3 -m json.tool

echo "\nDemo finished. Use the IDs above to explore further via /docs or the CLI." 
